name: Build EXE for Windows using PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-exe:
    runs-on: windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE using PyInstaller
      run: |
        pyinstaller --onefile -p src -n QtTinySA QtTinySA.py --window --clean -y -i tinySA.ico

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-exe
        path: dist/QtTinySA.exe